# Generated by Django 3.2.6 on 2021-08-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Ticker', models.CharField(max_length=20)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='PriceLookUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=200)),
                ('Ticker', models.CharField(max_length=20, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('Echo', 'Echo'), ('business_insider', 'Business Insider')], max_length=100)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.company')),
            ],
        ),
    ]
